/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Hoang
 */
public class QLBH_GUI extends javax.swing.JFrame {

    /**
     * Creates new form QLBH_GUI
     */
    public QLBH_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnedit = new javax.swing.JMenu();
        mninv = new javax.swing.JMenuItem();
        mnikh = new javax.swing.JMenuItem();
        mnincc = new javax.swing.JMenuItem();
        mniloai = new javax.swing.JMenuItem();
        mnimh = new javax.swing.JMenuItem();
        mnihd = new javax.swing.JMenuItem();
        mnicthd = new javax.swing.JMenuItem();
        mniexit = new javax.swing.JMenuItem();
        mnhelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BÁN HÀNG");

        mnedit.setText("Edit");

        mninv.setText("Nhân viên");
        mninv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninvActionPerformed(evt);
            }
        });
        mnedit.add(mninv);

        mnikh.setText("Khách hàng");
        mnikh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhActionPerformed(evt);
            }
        });
        mnedit.add(mnikh);

        mnincc.setText("Nhà cung cấp");
        mnincc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninccActionPerformed(evt);
            }
        });
        mnedit.add(mnincc);

        mniloai.setText("Loại hàng");
        mniloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniloaiActionPerformed(evt);
            }
        });
        mnedit.add(mniloai);

        mnimh.setText("Mặt hàng");
        mnimh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnimhActionPerformed(evt);
            }
        });
        mnedit.add(mnimh);

        mnihd.setText("Hóa đơn");
        mnihd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihdActionPerformed(evt);
            }
        });
        mnedit.add(mnihd);

        mnicthd.setText("Chi tiết hóa đơn");
        mnicthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnicthdActionPerformed(evt);
            }
        });
        mnedit.add(mnicthd);

        mniexit.setText("Thoát");
        mniexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniexitActionPerformed(evt);
            }
        });
        mnedit.add(mniexit);

        jMenuBar1.add(mnedit);

        mnhelp.setText("Help");
        jMenuBar1.add(mnhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mninvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninvActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new NV_GUI().setVisible(true);
    }//GEN-LAST:event_mninvActionPerformed

    private void mnikhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new KH_GUI().setVisible(true);
    }//GEN-LAST:event_mnikhActionPerformed

    private void mninccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninccActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new NCC_GUI().setVisible(true);
    }//GEN-LAST:event_mninccActionPerformed

    private void mniloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniloaiActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new Loai_GUI().setVisible(true);
    }//GEN-LAST:event_mniloaiActionPerformed

    private void mnimhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnimhActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new MH_GUI().setVisible(true);
    }//GEN-LAST:event_mnimhActionPerformed

    private void mnihdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihdActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new HD_GUI().setVisible(true);
    }//GEN-LAST:event_mnihdActionPerformed

    private void mnicthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnicthdActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new CTHD_GUI().setVisible(true);
    }//GEN-LAST:event_mnicthdActionPerformed

    private void mniexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniexitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_mniexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLBH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLBH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLBH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLBH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLBH_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnedit;
    private javax.swing.JMenu mnhelp;
    private javax.swing.JMenuItem mnicthd;
    private javax.swing.JMenuItem mniexit;
    private javax.swing.JMenuItem mnihd;
    private javax.swing.JMenuItem mnikh;
    private javax.swing.JMenuItem mniloai;
    private javax.swing.JMenuItem mnimh;
    private javax.swing.JMenuItem mnincc;
    private javax.swing.JMenuItem mninv;
    // End of variables declaration//GEN-END:variables
}
